syntax = "proto3";

package recommendation;

// Define the service
service RecommendationService {
    // Generate recommendations for a specific user
    rpc GetRecommendations (RecommendationRequest) returns (RecommendationResponse) {}
}

// Request payload
message RecommendationRequest {
    string username = 1;
}

// Single article representation
message Article {
    string title = 1;
    string date = 2;
    string source = 3;
    string link = 4;
    string image = 5;
    string content = 6;
    string author = 7;
    string category = 8;
    float score = 9; // ML probability score
}

// Response payload
message RecommendationResponse {
    bool success = 1;
    string message = 2;
    repeated Article recommendations = 3;
}
