# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recommendation.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'recommendation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14recommendation.proto\x12\x0erecommendation\")\n\x15RecommendationRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"\x95\x01\n\x07\x41rticle\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x0c\n\x04link\x18\x04 \x01(\t\x12\r\n\x05image\x18\x05 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x06 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x07 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x08 \x01(\t\x12\r\n\x05score\x18\t \x01(\x02\"l\n\x16RecommendationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x30\n\x0frecommendations\x18\x03 \x03(\x0b\x32\x17.recommendation.Article2~\n\x15RecommendationService\x12\x65\n\x12GetRecommendations\x12%.recommendation.RecommendationRequest\x1a&.recommendation.RecommendationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommendation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECOMMENDATIONREQUEST']._serialized_start=40
  _globals['_RECOMMENDATIONREQUEST']._serialized_end=81
  _globals['_ARTICLE']._serialized_start=84
  _globals['_ARTICLE']._serialized_end=233
  _globals['_RECOMMENDATIONRESPONSE']._serialized_start=235
  _globals['_RECOMMENDATIONRESPONSE']._serialized_end=343
  _globals['_RECOMMENDATIONSERVICE']._serialized_start=345
  _globals['_RECOMMENDATIONSERVICE']._serialized_end=471
# @@protoc_insertion_point(module_scope)
